spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
security:
  jwt:
    secret: ${JWT_SECRET:YTJjZDhkNTIzZTA1M2E1NTY0NGU0MDA0YzY1NjJkNjk=}
    expiration-ms: 3600000
    refresh-exp-ms: 604800000
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
