spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
