spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration-ms: ${SECURITY_JWT_EXPIRATION-MS:3600000}
    refresh-exp-ms: ${SECURITY_JWT_REFRESH-EXP-MS:604800000}
